### PR TITLE
chore: migrate to GitHub actions

### PR DESCRIPTION
**Pull request by dnwe**
The Travis build(s) are no longer functional, so attempt to port the existing behaviour to equivalent GitHub Actions workflows.

### CODE REVIEW

**Comment by dnwe** [comment]
I tested these actions on my own fork and they seemed to be working well

**Review by frese — COMMENTED** [review]
Is it possible for you to keep the 4 space indent ?

**Comment by dnwe** [comment]
@frese on app.go? it has just has the standard gofmt applied, which golang cli-lint checks, which is tabbed indentation

**Comment by dnwe** [comment]
Ref: https://github.com/golang/go/wiki/CodeReviewComments#gofmt

**Pull request merged**
